app:
  app_name: 'auth-service'
  log_level: 'INFO'
  production: false

http:
  port: ':8080'
  timeout: '30s'
  shutdown_timeout: '15s'
  read_timeout: '15s'
  write_timeout: '60s'

db:
  host: 'localhost'
  port: ':27017'
  db_name: 'auth-service'

token:
  time_to_live_access: "1m"
  time_to_live_refresh: "4m"